#install.packages(c("devtools","qdap","tm","stopwords"))
#devtools::install_github("nurandi/katadasaR")
library(readxl)
library(dplyr)
library(stringr)
library(tm)
df <- read_excel("~/Documents/KULIAH/DatasetR.xlsx")
df2 <- casefold(df, upper = FALSE)
df3 <- removeNumbers(df[[1]])
df4 <- removePunctuation(df[[1]])